---
slug: :Boujanai_store
depends:
  mikutter: 0.2.1.1119
  plugin:
  - mikustore
version: '1.1'
author: Boujanai
name: Boujanai's store
description: 中原のmikutterプラグインをみっくストアに追加するプラグイン
repository: git://github.com/Boujanai/Boujanai_store.git
